[Main]
library=0
IncludeUserRPL=0
AutoLoad=1
Compress=0
Calc48=0
KeepAll=0
UseDefaultEntryList=1
WarnRamChanges=1
LoadOnly=0
EMUVisible=1
ProjectTab=1
InformHeight=50
EntryPointList=
Title=New_Project
Config=
ExtPrg=
Message=
Romid=200
Slot=0
Emu48Ram=C:\Users\julien\Documents\Debug4x\Emu\default 48GX.e48
Emu48Port2=C:\Program Files (x86)\Hewlett-Packard\Debug4x\Emu\default 48GX.bin
Emu49Ram=C:\Users\julien\Documents\emu50bis.e49
FilePath=smhp50game.hp
DirPath=
RPL_INCLUDE=
SasmParams=
LRFiles=
[Files]
file1=smhp_game_50.s
[Edit]
edit2=>smhp_game_50.s
edit3=C:\Users\julien\Documents\hp48games\HP50\SuperMarioHP50\editor\smhp_editor_50.s
edit4=C:\Users\julien\Documents\hp48games\HP50\Misc\grayscales.s
